### Register

POST http://localhost:3000/api/login/register HTTP/1.1
Content-Type: application/json

{
    "email": "jenna.doe@email.com",
    "name": "Jenna Doe",
    "mobile": "00000",
    "password": "test123"
}

### Signin

POST http://localhost:3000/api/login/signin HTTP/1.1
Content-Type: application/json

{
    "email": "brett@example.com",
    "password": "brettpass"
}

### Signout

GET http://localhost:3000/api/login/signout HTTP/1.1

### User data

GET http://localhost:3000/api/user/me HTTP/1.1

### Create group

POST http://localhost:3000/api/group HTTP/1.1
Content-Type: application/json

{
    "name": "New group",
    "maxPrice": 288,
    "location": "London",
    "date": "{{$datetime iso8601}}",
    "members": [
        {
        "email": "jenna.doe@email.com",
        "name": "Jenna Doe",
        "mobile": "00000"
        },
        {
        "email": "lore@email.com",
        "name": "`Lore G",
        "mobile": "11111"
        }
    ]

}
