### Register

POST http://localhost:3005/api/login/register HTTP/1.1
Content-Type: application/json

{
    "email": "jenna.doe@email.com",
    "name": "Jenna Doe",
    "mobile": "00000",
    "password": "test123"
}

### Signin

POST http://localhost:3005/api/login/signin HTTP/1.1
Content-Type: application/json

{
    "email": "brett@example.com",
    "password": "brettpass"
}

### Signout

GET http://localhost:3005/api/login/signout HTTP/1.1

### User data

GET http://localhost:3005/api/user/me HTTP/1.1

### Create group

POST http://localhost:3005/api/group HTTP/1.1
Content-Type: application/json

{
    "name": "New group",
    "maxPrice": 288,
    "location": "London",
    "date": "{{$datetime iso8601}}",
    "members": [
        {
        "email": "jenna.doe@email.com",
        "name": "Jenna Doe",
        "mobile": "00000"
        },
        {
        "email": "lorenagil1990@gmail.com",
        "name": "Lore G",
        "mobile": "11111"
        },
                {
        "email": "elias@email.com",
        "name": "Elias",
        "mobile": "123"
        },
                {
        "email": "ana@email.com",
        "name": "Ana G",
        "mobile": "13333"
        }
    ]
}

### Update group

PUT http://localhost:3005/api/group/33fa1c78-0c43-4a37-9440-477b18c3c9c7 HTTP/1.1
Content-Type: application/json

{
    "name": "New group updated",
    "maxPrice": 50,
    "location": "Valencia",
    "date": "{{$datetime iso8601}}",
    "members": [
        {
        "email": "jenna.doe@email.com",
        "name": "Jenna Doe",
        "mobile": "00000"
        },
        {
        "email": "lore@email.com",
        "name": "Lore G",
        "mobile": "11111"
        },
        {
        "email": "elias@email.com",
        "name": "Elias",
        "mobile": "123"
        }
    ]
}

### Delete group

DELETE http://localhost:3005/api/group/7b640531-6cea-499a-91bd-0f695686c691 HTTP/1.1
Content-Type: application/json

### Send emails

GET http://localhost:3005/api/group/d326b42d-1d85-4080-a775-8b1d27a55691/send HTTP/1.1
