# @hostname = http://localhost:3005
@hostname = https://secretsantabackend-production.up.railway.app

### Register

POST {{hostname}}/api/login/register HTTP/1.1
Content-Type: application/json

{
    "email": "jenna.doe@email.com",
    "name": "Jenna Doe",
    "mobile": "00000",
    "password": "test123"
}

### Signin

POST {{hostname}}/api/login/signin HTTP/1.1
Content-Type: application/json

{
    "email": "brett@example.com",
    "password": "brettpass"
}

### Signout

GET {{hostname}}/api/login/signout HTTP/1.1

### User data

GET {{hostname}}/api/user/me HTTP/1.1

### Create group

POST {{hostname}}/api/group HTTP/1.1
Content-Type: application/json

{
    "name": "New group",
    "maxPrice": 288,
    "location": "London",
    "date": "{{$datetime iso8601}}",
    "members": [
        {
        "email": "jenna.doe@email.com",
        "name": "Jenna Doe",
        "mobile": "00000"
        },
        {
        "email": "lorena@mail.com",
        "name": "Lore G",
        "mobile": "11111"
        },
                {
        "email": "elias@email.com",
        "name": "Elias",
        "mobile": "123"
        },
                {
        "email": "ana@email.com",
        "name": "Ana G",
        "mobile": "13333"
        }
    ]
}

### Update group

PUT {{hostname}}/api/group/252d1e21-8c67-466e-b9f6-9b23a448b2f9 HTTP/1.1
Content-Type: application/json

{
    "name": "New group updated",
    "maxPrice": 50,
    "location": "Valencia",
    "date": "{{$datetime iso8601}}",
    "members": [
    ]
}

### Delete group

DELETE {{hostname}}/api/group/7b640531-6cea-499a-91bd-0f695686c691 HTTP/1.1
Content-Type: application/json

### Send emails

POST {{hostname}}/api/group/ec47496c-7b48-4784-8cbc-d833448df080/send HTTP/1.1
Content-Type: application/json

{
        "members": [
        {
        "email": "jenna.doe@email.com",
        "name": "Jenna Doe 2",
        "mobile": "00000"
        },
        {
        "email": "lorenagil1990@gmail.com",
        "name": "Lore G",
        "mobile": "11111"
        }
    ]
}
